on:
  workflow_dispatch:
  push:
    branches:
      - master

# 自定义环境变量


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: config
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          path: source
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: website
          path: public
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install


      # 生成并部署
      - name: Deploy
        run: |
          npx hexo generate
          cd public 
          git config --global user.name 'ccreater222'
          git config --global user.email 'ccreater222@users.noreply.github.com'
          git add *
          git commit -am "Automated generation"
          git push origin website
